// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {network} from '../models';
import {main} from '../models';

export function GetConfig():Promise<config.AppConfig>;

export function GetInterfaces():Promise<Array<network.NetworkInterface>>;

export function GetIsSniffing():Promise<boolean>;

export function GetStats():Promise<main.Stats>;

export function HealthCheck():Promise<main.HealthStatus>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function StartSniffer():Promise<void>;

export function StopSniffer():Promise<void>;

export function TriggerTestAlert():Promise<void>;
