// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function GetIsSniffing() {
  return window['go']['main']['App']['GetIsSniffing']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartSniffer() {
  return window['go']['main']['App']['StartSniffer']();
}

export function StopSniffer() {
  return window['go']['main']['App']['StopSniffer']();
}

export function TriggerTestAlert() {
  return window['go']['main']['App']['TriggerTestAlert']();
}
